### ISSUE TITLE
Error join & leave event

### ISSUE THREAD

**Issue by ItzRonaldMLG** [TeamVK/TokenEnchant#7]
**Describe the bug**
Error

**To Reproduce**
Join with something enchanted in inventory.

**Expected behavior**
No error

**Screenshots**
Error: https://pastebin.com/DTJXK7e9

**Environment (please complete the following information):**
Spigot 1.16.5-R0.1

**Configuration:**
https://pastebin.com/fY6rSPjt

**Comment by vk2gpz** [comment]
Please report an issue at vk2gpz.freshdesk.com
